---
- name: install pgbouncer repository
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-redhat-repo-latest.noarch.rpm"
  when: ansible_os_family == 'RedHat'

- name: install pgbouncer
  yum:
    name: pgbouncer
    state: "{{ pgbouncer_install_state }}"
    update_cache: yes
    disable_gpg_check: yes
  when: ansible_os_family == 'RedHat'

- name: install pgbouncer
  apt:
    pkg: pgbouncer
    state: "{{ pgbouncer_install_state }}"
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: check pgbouncer user exists
  getent:
    database: passwd
    key: pgbouncer
  register: pgbouncer_exists
  ignore_errors: true

- name: setting pgbouncer user/group
  set_fact: 
    pgbouncer_owner: "{{ 'postgres' if pgbouncer_exists.failed else 'pgbouncer' }}"
    pgbouncer_group: "{{ 'postgres' if pgbouncer_exists.failed else 'pgbouncer' }}"

- name: install postgresql-client
  apt:
    pkg: postgresql-client
    state: present
  when: (ansible_os_family == 'Debian') and pgbouncer_install_psql

- name: pgbouncer directory exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pgbouncer_owner }}"
    group: "{{ pgbouncer_group }}"
  with_items:
    - /var/log/pgbouncer
    - /var/run/pgbouncer

- name: template config files
  template:
    src: "{{ item }}"
    dest: /etc/pgbouncer/{{ item | basename | splitext | first }}
    backup: yes
    owner: "{{ pgbouncer_owner }}"
    group: "{{ pgbouncer_group }}"
    mode: 0640
  with_fileglob: templates/*
  notify: "{{ pgbouncer_service_state }} pgbouncer"

- name: start pgbouncer at startup
  service:
    name: pgbouncer
    enabled: yes
    state: started
